### ISSUE TITLE
can pyocd work with blackmagic probe ?

### ISSUE THREAD

**Issue by liboyangbj** [blackmagic-debug/blackmagic#1805] opened 2024-04-22 13:35 UTC
can pyocd work with blackmagic probe ?

thanks

**Comment by dragonmux** [comment] 2024-04-22 17:56
If that project chooses to implement our remote protocol, yes.. though given BMP itself is a full-featured GDB server in a dongle we're not sure why you would exactly want to do that vs just using BMP. The only reason we can think of is if there's a target not supported by this project and you don't want to implement support here.

Note that BMDA isn't doing anything special to be able to drive a probe that's running the firmware from a host machine - it's purely talking the Black Magic Debug remote protocol to the probe to use the probe as a semi-dumb adaptor more akin to a J-Link or a CMSIS-DAP adaptor, ignoring the GDB server packed in the firmware, w/ all the target logic run on the host.

**Comment by dragonmux** [comment] 2024-04-23 02:15
Ah, so - you don't want to `add-inferior` to set the file used - you want to either use the `file` option or get it passed on the command line. "inferiors" are programs being debugged, but your host isn't running the .elf to debug it - your target is. This is likely the cause of most of your troubles here. Additionally, you have to ask BMD to scan the bus for targets.

What you likely want to do is:
```gdb
define target remote
file $arg2
target extended-remote $arg0
monitor swd_scan # this might also want to be `monitor jtag_scan` depending on if your target is on JTAG or SWD.
attach $arg1
end
```

**Comment by liboyangbj** [comment] 2024-04-23 02:22
thanks
I'll try it later

**Comment by liboyangbj** [comment] 2024-04-23 02:53
Running well. I added “load” under “attach $arg1”.
Otherwise, CLion will not be able to run to the breakpoint. I think it may be a problem with CLion.

define target remote
file $arg2
target extended-remote $arg0
# this might also want to be `monitor jtag_scan` depending on if your target is on JTAG or SWD.
monitor swd_scan
attach $arg1
load
end

**Comment by dragonmux** [comment] 2024-04-23 02:59
Glad to hear it - unless there's anything else that seems to be amiss, we'll close this as solved. The "Won't fix" label is just to document that nothing our side was actually broken here and that it's an issue in a product outside of this project.

**Comment by liboyangbj** [comment] 2024-04-23 03:07
Thanks
😊😊😊

**Closed** 2024-04-23 03:12 UTC
Labels: Won't fix, GDB
