### ISSUE TITLE
Windows 11 - Drivers Missing ?

### ISSUE THREAD

**Issue by nurquhar** [blackmagic-debug/blackmagic#1022] opened 2022-05-26 17:04 UTC
OK I have a Black Magic Probe for a couple of years now, it works great on my Windows 10 laptop. Plug it in and away you go, no usb driver install was required.

I have now upgraded my old Windows 10 machine to a new Dell Laptop which has Windows 11. I connect my usb Black Magic Probe and in Device Manager I see the devices under 'Other Devices' and they both have exclamation marks against the icons. I guess this means the drivers are missing. 

So where to get the drivers or is there another fix ???

I tried Dell Support, they did what I did and checked for any driver updates and then they just gave up as being out of their depth.

Here is what I see in Device Manager.

![image](https://user-images.githubusercontent.com/34193510/170535541-e58f839d-68a6-479d-8a1b-9578ede9c542.png)

**Comment by dragonmux** [comment] 2022-05-26 19:41
Your BMP is already working (the two serial ports show up, the lower numbered is the GDB endpoint, and the higher is the USB UART connected to the UART connections on the back of the board) - the trace capture and firmware upgrade endpoints only need configuring if you need to do tracing or upgrade the firmware.

Our recommended way for now on Windows for setting those up is to use [Zadig](https://zadig.akeo.ie/) and bind both to the WinUSB driver.

**Comment by nurquhar** [comment] 2022-05-28 15:42
So is Zadig now required just to use the program function of BMP ?  As it does not seem to work out the box on Win 11, I get this warning and it hangs. The same happens if I use COM3 or COM4 in my script.
![image](https://user-images.githubusercontent.com/34193510/170832160-6eb055e8-f8a2-4f90-95b2-b153a31f90ee.png)

Removing the other clutter from the USB bus I have this in Device Manger so COM3 & 4 are associated with BMP.
![image](https://user-images.githubusercontent.com/34193510/170832222-42f3539c-7949-4eef-a57e-4a4edc69ac99.png)

On the windows 10 machine it programs fine using COM10 in my script.
![image](https://user-images.githubusercontent.com/34193510/170832271-c28ed661-0aea-4889-9978-09c41afbbd1a.png)

However the device manager looks a little different
![image](https://user-images.githubusercontent.com/34193510/170832301-da08041b-4c93-4e38-90e1-12585b80f258.png)

**Comment by dragonmux** [comment] 2022-05-28 15:47
Zadig has always been required for Windows to bind drivers to the DFU and Trace/Capture interfaces - this is not a new requirement. Most likely you (or if it's a shared machine, someone else) did this a long time ago on the Windows 10 machine.

However, that's separate from being able to use BMP to program a target which only uses the "COM ports" you see (COM3 for the GDB server which is what you show your script using in the second set of screenshots). You can safely completely ignore the DFU and Trace/Capture interfaces, they're not the cause of your failures. We'd suggest that, as COM10 works with your script already, use the Windows properties dialog for "USB Serial Device (COM3)" to switch it to binding as COM10 and try again.

**Comment by nurquhar** [comment] 2022-05-28 16:02
Ok I used Zadig and now the missing drivers are fixed. I also change COM3 to be COM10 on my Win 11 m/c, not sure why this is necessary as I can edit the port in my script. 
![image](https://user-images.githubusercontent.com/34193510/170833177-00c1b64c-676e-4487-8e89-31838079a1bf.png)

However even with using COM10 the same thing happens 
![image](https://user-images.githubusercontent.com/34193510/170833203-0c791af6-8688-48ba-88ec-b5b5e4b238c0.png)

Here is the script also
![image](https://user-images.githubusercontent.com/34193510/170833221-f4dea175-36dc-4e56-9190-c63628fc918a.png)

**Comment by dragonmux** [comment] 2022-05-28 16:14
Ah, we assumed that changing the port in your script was more complicated (you can put it back if you like) - but fair enough. As for your GDB problems.. without knowing what exact version of GDB you're trying to use and the providence of the toolchain we unfortunately can't be of much further help.

The only extra things we can offer are to check that what is now COM10 is definitely for interface 0 (using the Windows driver properties dialog) to gain some confidence that it's definitely the GDB server interface, and run GDB manually with each of the commands you're passing it with -ex to see what, where, why, and how it's failing with more detail.

Of important note, GDB 11 and 12 will **not** work because of some known bugs in GDB itself, so you must use GDB 10.

**Comment by nurquhar** [comment] 2022-05-28 16:40
I changed back to COM3. Tried manual steps, fails on telling it about COM3 and hangs (same happens for COM4)
![image](https://user-images.githubusercontent.com/34193510/170834178-48f99652-e855-4d1f-b24a-9f423856f7ee.png)

Run same on Win 10 m/c : 
![image](https://user-images.githubusercontent.com/34193510/170834510-d3e4338d-fc84-4e8e-8f90-7ee9985f7427.png)
 To me it looks like I am running the same command on Win 11 as Win 10.
 So how to find the GDB version ?

**Comment by dragonmux** [comment] 2022-05-28 17:03
it's in the output you provided - first line it outputs - GDB 8.0.50 from 2017. Also, note you have an extra backslash on the end of COM3 in your Windows 11 invocation - that won't work.

**Comment by esden** [comment] 2022-05-28 17:14
Hi @nurquhar,

You should try using the other com port. Sometimes windows is being annoying and likes to shuffle the com ports for no reason. I have just installed win11 to test things out. It is a clean install without Zadig drivers installed. (They are not necessary unless you have to update the firmware on the BMP itself as @dragonmux described.)

Here is how that looks like in my Win11 device manager:
<img width="216" alt="Screen Shot 2022-05-28 at 9 48 22 AM" src="https://user-images.githubusercontent.com/17334/170835586-981ab304-ace7-4532-af60-92ab91c3c6b6.png">

I used the official [arm embedded binary release](https://developer.arm.com/downloads/-/gnu-rm) for testing.

As mentioned above, I had to use the second com port instead of the first one. But it works fine without locking up. When remote connection hangs it is usually because the USBUSART port is selected instead of the GDB serial port.

Here is the output from the Win11 machine.

<img width="959" alt="Screen Shot 2022-05-28 at 9 56 24 AM" src="https://user-images.githubusercontent.com/17334/170835662-98833335-d122-471d-ac6b-09152766eb13.png">

I hope you can figure out your setup.

**Comment by nurquhar** [comment] 2022-05-28 21:59
Thanks for all the help guys, I have if figured out and working with COM4 as suggested 👍 The extra slash did not help either, thanks for pointing this out.

![image](https://user-images.githubusercontent.com/34193510/170843892-848c4b1c-aa86-4d4a-990f-5ec3d93441f4.png)

It seems testing with COM3 would fail because it was the wrong COM port. However simply changing the script to COM4 after a failure with COM3 and re-running was insufficient. Re-running the script with COM4 set would also then fail. However COM4 will work after a failure with COM3 if I cycle the USB connection (Unplug and plugin again) !!!

**Comment by dragonmux** [comment] 2022-05-28 22:02
Glad you got it working at last :) going to close the issue for now, but if you encounter any more problems with BMP itself, you'd be welcome to open a new issue.

**Closed by dragonmux** 2022-05-28 22:02 UTC

**Comment by esden** [comment] 2022-05-28 22:05
I am also glad to hear that you managed to get things to work. Additionally to what @dragonmux said you can also [join our discord server](https://1bitsquared.com/pages/chat) and ask your questions in the #blackmagic channel where we can give you some real time support. :)
