### ISSUE TITLE
bmp_remote: Problems with remote_adiv5_low_access and remote_adiv5_ap_write

### ISSUE THREAD

**Issue by UweBonnes** [blackmagic-debug/blackmagic#695] opened 2020-07-14 12:15 UTC
On the STM32MP157C-DK2 with the stlink firmware (ST_BOOTLOADER=1), the STM32MP1 is only visible once. On a second run, only TARGETID is readable. Reboot of the stlink (dfu-util -e; stlink-tool) gets the STM32MP1  visible again for one run. 

This points to a problem with BMP, as the MP1 debug unit is not power reset by that procedure.

Commenting out the assignment to dp->low_access and dp->ap_write in remote_adiv5_dp_defaults() allows multiple "blackmagic -t" runs to succeed.

Return false as first command in cortexa_probe() allows multiple successfull "blackmagic -t" runs in both cases.

This happens when the STM32MP1 is in boot mode, e.g. boot from SD card but card not plugged.

**Comment by esden** [comment] 2021-12-16 00:54
Do you have a proposed solution for this? How would you resolve this?

**Comment by esden** [comment] 2022-08-02 02:02
I can't reproduce it, I am closing it for now.

**Closed by esden** 2022-08-02 02:02 UTC
Labels: Bug, Can't reproduce
